### ISSUE TITLE
What to do when restart robot controller?

### ISSUE THREAD

**Issue by ScottYang1982** [ros-industrial/abb_librws#124]
@jontje,
  If robot controller is restarted ,then the current rws interface will lost its connection with the robot. But how to restore the connection automatically on restart of robot controller?
Thank you

**Comment by jontje** [comment]
Hi @ScottYang1982,

Can you provide more context about how you use `abb_librws`?

For example, if your application is polling for data, then it should automatically connect again after the robot controller has been restarted. Assuming the polling is continued during the restart.

However, if you have, for example, set up RWS subscriptions, then they won’t be resumed after the robot controller restart (at least as far as I know). In that case you need to reregister the subscriptions.

**Comment by gavanderhoorn** [comment]
I'm going to assume this is no longer a problem for you @ScottYang1982 and close this.

If you still have questions, please post a comment and we can re-open.
