### ISSUE TITLE
Can this Lib control IRB6700 abb robot?

### ISSUE THREAD

**Issue by wenwenqingqing** [ros-industrial/abb_librws#137]

**Comment by jontje** [comment]
You can use this library with all ABB robots that runs on the `IRC5` controller with a `RobotWare 6` system.

**Comment by gavanderhoorn** [comment]
In other words: the entire library is *manipulator agnostic*.

**Comment by gavanderhoorn** [comment]
As this is not an actual issue with the library here, I'm going to close it.

Feel free to keep commenting on it of course.
