### ISSUE TITLE
Convert to pure CMake package

### ISSUE THREAD

**Issue by gavanderhoorn** [ros-industrial/abb_librws#3]
Adapt `CMakeLists.txt` so we can accomodate building the library without Catkin / in a non-ROS (build) environment.

**Comment by gavanderhoorn** [comment]
Edit: as there is no ROS-specific functionality in this package, we should migrate it to be a pure CMake package.

The manifest can remain, and this would allow us to still build it in a ROS workspace (by setting [build_type](https://www.ros.org/reps/rep-0127.html#build-type) to `cmake`).

**Comment by traversaro** [comment]
> Edit: as there is no ROS-specific functionality in this package, we should migrate it to be a pure CMake package. All `catkin_*` calls should be removed.
> 
> The manifest can remain, and this would allow us to still build it in a ROS workspace (by setting [build_type](https://www.ros.org/reps/rep-0127.html#build-type) to `cmake`).
> 
> (this would also immediately make non-ROS builds possible, without needing two build scripts or undesirable detection/if-else constructs)

That is great. Just to understand, the same applies to `abb_libegm`? If that is the case, what changed w.r.t. to the requirement of being able to build the package with `catkin_make` mentioned in https://github.com/ros-industrial/abb_libegm/issues/3#issuecomment-409187490 ?

**Comment by gavanderhoorn** [comment]
> Just to understand, the same applies to `abb_libegm`? 

Yes.

> If that is the case, what changed w.r.t. to the requirement of being able to build the package with `catkin_make` mentioned in [ros-industrial/abb_libegm#3 (comment)](https://github.com/ros-industrial/abb_libegm/issues/3#issuecomment-409187490) ?

ROS 2 and the existence of Colcon.

Additionally, `catkin_tools` may be used with ROS 1.

**Comment by jontje** [comment]
I have created a new [branch](https://github.com/jontje/abb_librws/tree/plain_cmake) for converting the package into a plain cmake package.

I.e. similar rationale as in this comment https://github.com/ros-industrial/abb_libegm/issues/3#issuecomment-552378566.

**Comment by gavanderhoorn** [comment]
Looks like #69 was merged, so closing.

Thanks @traversaro  and @jontje :+1:
