### ISSUE TITLE
abb_librws_export.h not found

### ISSUE THREAD

**Issue by ScottYang1982** [ros-industrial/abb_librws#92]
Hi,
 why "abb_librws_export.h" is not available but referenced in "rws_commn.h"?????

**Comment by gavanderhoorn** [comment]
That file is generated as part of the build.

It's not a file stored in the repository.

**Comment by gavanderhoorn** [comment]
As this is not an issue with the code in this repository, I'm going to close it.

Do feel free to keep commenting on it of course.
